import type { CelloVisualEditorLabels } from "./types.js";

export const defaultLabels: CelloVisualEditorLabels = {
  bold: "Bold",
  cellScope: "cell",
  columnScope: "column",
  defaultsRow: "Defaults",
  deleteSheet: "Delete sheet",
  fillColor: "Fill color",
  h1: "Large heading",
  h2: "Medium heading",
  h3: "Small heading",
  headerRow: "Header",
  inherited: "Inherited",
  italic: "Italic",
  mergeLeft: "Merge with left",
  mergeUp: "Merge with top",
  newColumn: "New column",
  newRow: "New row",
  newSheet: "New sheet",
  noInheritedModifiers: "None",
  modifiers: "Modifiers",
  propertyScope: "Property scope",
  renameSheet: "Rename active sheet",
  selectedColumn: "Column",
  selectedRow: "Row",
  rowScope: "row",
  rowsMode: "Rows",
  selectedCellSource: "Selected cell source",
  source: "Source",
  strike: "Strikethrough",
  tableGroup: "Table",
  textColor: "Text color",
  textGroup: "Text",
  tone: "Tone",
  toolbar: "Visual editor toolbar",
  workbook: "Visual spreadsheet editor",
  workbookSheets: "Workbook sheets",
  columnsMode: "Columns",
  defaultOption: "Default",
  columnsNormal: "Normal",
  columnsFit: "Fit",
  rowsEllipsis: "Ellipsis",
  rowsWrap: "Wrap",
  fit: "Fit",
  width: "Width",
  wrap: "Wrap",
  height: "Height",
  filterAndSort: "Filter & sort",
  allRows: "All rows",
  clearView: "Clear view",
  savedView: "Saved view",
  filterColumn: "Filter column",
  noSort: "No sort",
  sortAscending: "A–Z",
  sortDescending: "Z–A",
  verticalMergeViewWarning: "Filtering is unavailable while this sheet contains vertical merges."
};
